# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM node:lts-alpine AS builder
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm ci --ignore-scripts

# Copy source and build
COPY . .
RUN npm run build

# Production image
FROM node:lts-alpine
WORKDIR /app

# Copy built files and production deps
COPY package.json package-lock.json .
RUN npm ci --production --ignore-scripts
COPY --from=builder /app/dist ./dist

# Default command
CMD ["node", "dist/index.js"]
